server:
  port: 8761

spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8769/eureka/